[package]
name = "day-03"
version = "0.1.0"
authors = ["Nikolai Øllegaard <nikolai@oellegaard.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared = { path = "../shared" }
itertools = "0.9.0"
